### ISSUE TITLE
differentiate between sequelize bulkcreate and stream bulkCreate

### ISSUE THREAD

**Issue by matt212** [joeybaker/sequelize-stream#10]
Hi, 
how do i differentiate between bulkcreate  command of sequelize from sequelize-stream
any pointers!

**Comment by joeybaker** [comment]
Currently, there's no way to do that. The idea is to treat _all_ data going through sequelize as a stream; I've never encountered a place where I'd want that information. What's your use case?

**Comment by matt212** [comment]
Hi, 
thanks for prompt response my existing codebase 

```
var models = require('./models');
var sequelize = new Sequelize(config.development.database, config.development.username, config.development.password,{dialect:"postgres"});
var sequelizeStream = require('sequelize-stream');

function datadump(data) {
    ////console.log(JSON.stringify(data));

    return new Promises(function(resolve, reject) {
        const stream = sequelizeStream(sequelize)
        //stream.on('data', ({instance, event}) => console.log(event, instance.toJSON()))
        stream.on('data', function (instance, event) {
            resolve(instance);
        })

        models.srt.bulkCreate(data);
    })
}
```
Any pointers on same !

**Comment by joeybaker** [comment]
I'm not familiar with `Promises` does that allow you to `resolve` multiple times?

**Comment by matt212** [comment]
Hi, 
Promises as basically in case scenario is bluebird promise lib , 
rather than 
stream.on('data', function (instance, event) {
            resolve(instance);
        })
 there could be 
stream.on('end', function (instance, event) {
            resolve(instance);
        })
wherein we can resolve only once when streaming is completed !

**Comment by joeybaker** [comment]
Hmm…… I'm not aware of that feature of bluebird. Got a link to docs?

The reason why I'm asking: promises are intended to be setup and resolved once, where as a stream's `'data'` event callback is called many times. I suspect you're swallowing all but the first event.

FWIW, streams and promises aren't usually a good pairing. I'm not sure I'd try to mix them.

**Comment by matt212** [comment]
Hi @joeybaker ,
well "resolved " should be fired on "finish" event not on "data" event of stream  for conventional promise based codeflow purpose.
plus on data event would not applicable in my scenario since, I wanted to bulk insert *stream* into postgres, anyways closing this thread since i used 
https://github.com/brianc/node-pg-copy-streams/ to accomplish my task for bulk insert *streaming* into postgres
thanks for clarifications
